"use client";
import { useState } from "react";

const people=[
 {id:"avier",name:"亞維爾",role:"三主角之一／智慧之星辰神力持有者",facts:["二十歲出頭男性，洛恩城出身的平民青年。不是王族、貴族、王儲或騎士。","約 178cm，棕黑短髮自然凌亂，琥珀棕眼，身形修長結實，五官俊朗但保有平民青年氣質。初期穿著樸素實用，並非專業戰士。","善良、直率、有行動力與強烈同理心。看見他人陷入危險很難袖手旁觀，因此有時過於衝動。會害怕、猶豫、自責，並非完美勇者。","第一集洛恩城災難中受到智慧之星辰・凱洛斯選中。可察覺異常、魔力流動及敵人行動規律，但不能讀心、預知未來或全知；過度使用會造成精神負荷。","與菲蕾在災變前便已相識；葛蘭特是同行夥伴與經驗豐富的前輩，並非其護衛。"],note:"不是王子，也不是天生勇者。就一個會怕、會猶豫，看到別人出事又硬是沒辦法不管的普通青年。這種人才最麻煩。也是我最喜歡寫的那種。"},
 {id:"philae",name:"菲蕾",role:"三主角之一／生命之星辰神力持有者",facts:["二十歲出頭女性，洛恩城出身的普通平民。不是聖女、神官、王族或貴族。","約 165cm，栗棕色長髮、淺綠色眼睛，身形纖細勻稱，五官秀氣親和。平時穿著簡單實用，旅行後改穿方便行動的服裝。","溫柔、細膩、有同理心，善於察覺他人情緒，但並不軟弱。重要事情上相當固執，無法輕易放棄仍有機會拯救的人。","第一集受到生命之星辰・海拉選中。能力核心為生命、治療、生命感知與庇護；不能復活真正死亡的人，也不能無限制治療，大量使用會造成嚴重疲勞甚至失去意識。","與亞維爾彼此高度信任，葛蘭特為同行夥伴。不是主要戰鬥型角色。"],note:"再說一次，她不是聖女。她只是會把最後一塊麵包塞給別人，然後嘴硬說那塊本來就賣不掉。生命系最殘忍的地方，是她遲早得承認自己救不了所有人。"},
 {id:"grant",name:"葛蘭特・海瑟",role:"三主角之一／資深冒險者",facts:["約三十歲男性，長年接受公會委託的資深冒險者。不是王族、貴族、騎士、王儲護衛或亞維爾護衛。","約 185cm，高大精壯，深棕短髮、灰綠眼，五官成熟硬朗，偶有鬍渣與實戰留下的舊傷；主要使用長劍。","沉著、務實、可靠，習慣觀察後行動。重視準備與生存，但並非冷酷寡言、嗜殺或暴躁的人；表面不愛多管閒事，實際責任感很重。","沒有任何星辰神力。強項為長劍實戰、魔物知識、追蹤、野外求生、簡易急救與危機判斷；遇到打不贏的敵人會撤退或尋找弱點。","亞維爾與菲蕾是同行夥伴；對哲維與玩家初期皆沒有預設關係。"],note:"沒有神力。但我寫到最後才發現，他根本不需要。……這句不要給他看到，會得意。"},
 {id:"edmund",name:"愛德蒙・阿爾維恩",role:"阿爾維恩王儲／第一順位繼承人",facts:["二十七歲男性，阿爾維恩王國第一順位王位繼承人。不是原著三主角之一。","約 188cm，深金色短髮、冰藍色狹長眼，身形高挑挺拔，氣質沉靜威嚴。正式場合穿王室服飾；巡視城防或災區時偏向簡潔軍裝。","冷靜、理性、自律且責任感極重。習慣從整個王國衡量人口、資源、軍力與風險；並非冷血暴君，證據證明自己錯誤時願意修正決策。","沒有星辰神力。接受過劍術、騎術與軍事教育，核心能力是政治判斷、戰略規劃、情報分析與資源調度。","曾因哲維的言語自動扭曲，將他誤認為騷擾王儲的可疑人物並下令關入地牢；若情報獲得證實，會合理重新評估哲維。"],note:"很難溝通。不借內褲。幹，我根本沒要借。他生氣時反而更冷靜，這點寫小說很好用，落到作者本人頭上就很恐怖。"}
];
export default function CharactersPage(){const [active,setActive]=useState(people[0]);const [privateMode,setPrivateMode]=useState(false);const select=(p:typeof people[number])=>{setActive(p);setPrivateMode(false)};return <main className="characters-page"><header><p className="eyebrow">WHEN THE STARS FALL · PERSONNEL</p><h1>角色檔案</h1><p>依《當群星墜落》正式人物設定建檔；作者私人註記另行標示。</p></header><section className="character-console"><nav>{people.map((p,i)=><button className={active.id===p.id?"active":""} onClick={()=>select(p)} key={p.id}><span>0{i+1}</span><b>{p.name}</b><small>{p.role}</small></button>)}</nav><article key={active.id}><p className="eyebrow">OFFICIAL ARCHIVE / {active.id.toUpperCase()}</p><h2>{active.name}</h2><h3>{active.role}</h3><ul className="character-facts">{active.facts.map(f=><li key={f}>{f}</li>)}</ul><button className="private-toggle" onClick={()=>setPrivateMode(!privateMode)}>{privateMode?"收起作者註記":"偷看作者註記"}</button>{privateMode&&<div className="private-note"><small>不渡私人檔案／非官方人物資料</small><p>「{active.note}」</p><i>——黑色筆記本頁角潦草字跡</i></div>}</article></section></main>}
